apiVersion: v1
kind: Service
metadata:
  name: travel-ui
spec:
  type: LoadBalancer
  selector:
    service: travel-ui
  ports:
  - name: "travel-ui"
    port: 80
    targetPort: 80
  - name: "travel-ui-debug"
    port: 4080
    targetPort: 4080
